server:
  port: 8761

spring:
  application:
    name: ead-service-registry

ead:
  serviceRegistry:
    username: serviceregistry
    password: '${SERVICE_REGISTRY_PASSWORD}'

eureka:
  client:
    register-with-eureka: false #para nao registar servico eureka
    fetch-registry: false #para nao buscar um registro eurerka
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'