server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'optional:configserver:'
    cloud:
      config:
        discovery:
          service-id: ead-config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_notification_async
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  output:
    ansi:
      enabled: always

  rabbitmq:
    addresses: amqps://kwcolbzn:PyX2BbrQyxvU51JXNmtlO0Pv9uE76F6b@fish.rmq.cloudamqp.com/kwcolbzn

logging:
  level:
    com.ead: trace
    root: info
    org.springframework.web: debug
    org.hibernate: info

ead:
  broker:
    notificationCommandExhange: ead.notificationcommand
  queue:
    notificationCommandQueue: ead.notificationcommand.ms.notification
  key:
    notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost