server:
  port: 8888
spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chandimba/ead-config-server-repo.git
          default-label: master
          username: dismao16@gmail.com
          password: ${CONFIG_SERVER_GIT_PASSWORD}

ead:
  configServer:
    username: configserver
    password: '${CONFIG_SERVER_PASSWORD}'
  serviceRegistry:
    username: serviceregistry
    password: '${SERVICE_REGISTRY_PASSWORD}'

eureka:
  client:
    service-url:
      default-zone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
    instance:
      hostname: localhost