server:
  port: 8888
spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chandimba/ead-config-server-repo.git
          default-label: master
          username: dismao16@gmail.com
          password:

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost